#!/usr/bin/env python3
# hps2gmx_topol_converter written by Xianshi Liu @ Fudan University, 2022. 

from distutils.core import setup
from Cython.Build import cythonize
import os

os.chdir("src")

setup(name='hps2gmx topol converter app',
      ext_modules=cythonize("hps2gmx_topol_converter.py"))

os.system("mv *.so ..")